
# vim: set expandtab sw=4 ts=4 :

sudo: required

services:
    - docker

install:
  - go get github.com/optiopay/klar
  - export REPO="avhost/docker-matrix-riot"
  - sudo apt-get install curl

script:
  - docker build -t $REPO:clair .
  - mkdir -p /tmp/data
  - echo '-p 8765 -A 0.0.0.0 -c 3500' > /tmp/data/riot.im.conf
  - docker run -d -p "8765:8765" -v /tmp/data:/data --name container $REPO:clair
  - docker ps | grep -i container
  - sleep 5
  - curl -X GET http://0.0.0.0:8765 > /dev/null
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker run -d --name db arminc/clair-db:latest
  - docker run -d -p 6060-6061:6060-6061 --link db:postgres --name clair arminc/clair-local-scan:v2.0.1    
  - docker images
  - docker push $REPO:clair  
  - CLAIR_ADDR=http://localhost CLAIR_OUTPUT=High CLAIR_THRESHOLD=10 klar $REPO:clair 
    

after_failure:
  - docker logs container

after_success:
  - docker build -t $REPO .
  - docker build -t $REPO:$TRAVIS_BRANCH .
  - docker push $REPO      
  - docker push $REPO:$TRAVIS_BRANCH    
