
# vim: set expandtab sw=4 ts=4 :

sudo: required

services:
    - docker

install:
    - sudo apt-get install curl
    - docker build -t image .
    - mkdir -p /tmp/data
    - echo '-p 8765 -A 0.0.0.0 -c 3500' > /tmp/data/riot.im.conf
    - docker run -d -p "8765:8765" -v /tmp/data:/data --name container image

script:
    - docker ps | grep -i container
    - sleep 5
    - curl -X GET http://0.0.0.0:8765 > /dev/null

after_failure:
    - docker logs container

deploy:
    - provider: script
      skip_cleanup: true
      script: misc/deploy.sh
      on:
          branch: master

